### ISSUE TITLE
Ubuntu family is "not supported"

### ISSUE THREAD

**Issue by ikkaro** [voxpupuli/puppet-openvmtools#30]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby:  2.4.3p205
- Distribution: Ubuntu 16.04
- Module version: 2.0.1

## How to reproduce (e.g Puppet code you use)
In puppet code a block that contains:

```include ::openvmtools```

In hiera:
```
openvmtools::ensure: present
openvmtools::autoupgrade: false
openvmtools::uninstall_vmware_tools: false
```

## What are you seeing

open-vm-tools should be installed

## What behaviour did you expect instead

open-vm-tools is not installed

## Output log

2020-05-07 09:38:26,122 INFO  [qtp605093187-80149] [puppetserver] Scope(Class[Openvmtools]) Your operating system Ubuntu is unsupported and will not have the Open Virtual Machine Tools installed.

## Any additional information you'd like to impart
The hiera.yml includes this one: 
```
hierarchy:
  - name: 'OS Major Version'
    path: '%{facts.os.family}.%{facts.os.name}.%{facts.os.release.major}.yaml'
  - name: 'OS Name'
    path: '%{facts.os.family}.%{facts.os.name}.yaml'
  - name: 'OS Family'
    path: '%{facts.os.family}.yaml'
```

In Ubuntu 16 the facts returns this:
```
os
  family => "Debian",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
```
Release major is "16.04", but the yaml filename is "Debian.Ubuntu.16.yaml", then never matches and reports the os as unsupported. The filename should be "Debian.Ubuntu.16.04.yaml".
